// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/tjsoler-psd2/pkg/models/shared"
	"github.com/speakeasy-sdks/tjsoler-psd2/pkg/utils"
	"net/http"
)

// PostAutorizacionInicioPagoPathParamAspsp - Nombre del ASPSP al que desea realizar la petición.(BBVA, Banco Santander ...)
type PostAutorizacionInicioPagoPathParamAspsp string

const (
	PostAutorizacionInicioPagoPathParamAspspRedsys          PostAutorizacionInicioPagoPathParamAspsp = "redsys"
	PostAutorizacionInicioPagoPathParamAspspBbva            PostAutorizacionInicioPagoPathParamAspsp = "BBVA"
	PostAutorizacionInicioPagoPathParamAspspBbvapt          PostAutorizacionInicioPagoPathParamAspsp = "BBVAPT"
	PostAutorizacionInicioPagoPathParamAspspBbvabe          PostAutorizacionInicioPagoPathParamAspsp = "BBVABE"
	PostAutorizacionInicioPagoPathParamAspspBbvafr          PostAutorizacionInicioPagoPathParamAspsp = "BBVAFR"
	PostAutorizacionInicioPagoPathParamAspspBbvaeuk         PostAutorizacionInicioPagoPathParamAspsp = "BBVAEUK"
	PostAutorizacionInicioPagoPathParamAspspCaixabank       PostAutorizacionInicioPagoPathParamAspsp = "caixabank"
	PostAutorizacionInicioPagoPathParamAspspBancSabadell    PostAutorizacionInicioPagoPathParamAspsp = "BancSabadell"
	PostAutorizacionInicioPagoPathParamAspspBancosantander  PostAutorizacionInicioPagoPathParamAspsp = "bancosantander"
	PostAutorizacionInicioPagoPathParamAspspBancamarch      PostAutorizacionInicioPagoPathParamAspsp = "bancamarch"
	PostAutorizacionInicioPagoPathParamAspspBankoa          PostAutorizacionInicioPagoPathParamAspsp = "bankoa"
	PostAutorizacionInicioPagoPathParamAspspCajamar         PostAutorizacionInicioPagoPathParamAspsp = "cajamar"
	PostAutorizacionInicioPagoPathParamAspspArquia          PostAutorizacionInicioPagoPathParamAspsp = "arquia"
	PostAutorizacionInicioPagoPathParamAspspBff             PostAutorizacionInicioPagoPathParamAspsp = "BFF"
	PostAutorizacionInicioPagoPathParamAspspColonya         PostAutorizacionInicioPagoPathParamAspsp = "colonya"
	PostAutorizacionInicioPagoPathParamAspspEurocajarural   PostAutorizacionInicioPagoPathParamAspsp = "eurocajarural"
	PostAutorizacionInicioPagoPathParamAspspEvobanco        PostAutorizacionInicioPagoPathParamAspsp = "evobanco"
	PostAutorizacionInicioPagoPathParamAspspFiarebancaetica PostAutorizacionInicioPagoPathParamAspsp = "fiarebancaetica"
	PostAutorizacionInicioPagoPathParamAspspBancopichincha  PostAutorizacionInicioPagoPathParamAspsp = "bancopichincha"
	PostAutorizacionInicioPagoPathParamAspspUnicajabanco    PostAutorizacionInicioPagoPathParamAspsp = "unicajabanco"
	PostAutorizacionInicioPagoPathParamAspspCajasur         PostAutorizacionInicioPagoPathParamAspsp = "cajasur"
	PostAutorizacionInicioPagoPathParamAspspKutxabank       PostAutorizacionInicioPagoPathParamAspsp = "kutxabank"
	PostAutorizacionInicioPagoPathParamAspspBankinter       PostAutorizacionInicioPagoPathParamAspsp = "bankinter"
	PostAutorizacionInicioPagoPathParamAspspRenta4          PostAutorizacionInicioPagoPathParamAspsp = "renta4"
	PostAutorizacionInicioPagoPathParamAspspBce             PostAutorizacionInicioPagoPathParamAspsp = "BCE"
	PostAutorizacionInicioPagoPathParamAspspLaboralkutxa    PostAutorizacionInicioPagoPathParamAspsp = "laboralkutxa"
	PostAutorizacionInicioPagoPathParamAspspMediolanum      PostAutorizacionInicioPagoPathParamAspsp = "mediolanum"
	PostAutorizacionInicioPagoPathParamAspspOpenbank        PostAutorizacionInicioPagoPathParamAspsp = "openbank"
	PostAutorizacionInicioPagoPathParamAspspIbercaja        PostAutorizacionInicioPagoPathParamAspsp = "ibercaja"
	PostAutorizacionInicioPagoPathParamAspspSelfbank        PostAutorizacionInicioPagoPathParamAspsp = "selfbank"
	PostAutorizacionInicioPagoPathParamAspspInversis        PostAutorizacionInicioPagoPathParamAspsp = "inversis"
	PostAutorizacionInicioPagoPathParamAspspAndbank         PostAutorizacionInicioPagoPathParamAspsp = "andbank"
	PostAutorizacionInicioPagoPathParamAspspWizink          PostAutorizacionInicioPagoPathParamAspsp = "wizink"
)

func (e PostAutorizacionInicioPagoPathParamAspsp) ToPointer() *PostAutorizacionInicioPagoPathParamAspsp {
	return &e
}

func (e *PostAutorizacionInicioPagoPathParamAspsp) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "redsys":
		fallthrough
	case "BBVA":
		fallthrough
	case "BBVAPT":
		fallthrough
	case "BBVABE":
		fallthrough
	case "BBVAFR":
		fallthrough
	case "BBVAEUK":
		fallthrough
	case "caixabank":
		fallthrough
	case "BancSabadell":
		fallthrough
	case "bancosantander":
		fallthrough
	case "bancamarch":
		fallthrough
	case "bankoa":
		fallthrough
	case "cajamar":
		fallthrough
	case "arquia":
		fallthrough
	case "BFF":
		fallthrough
	case "colonya":
		fallthrough
	case "eurocajarural":
		fallthrough
	case "evobanco":
		fallthrough
	case "fiarebancaetica":
		fallthrough
	case "bancopichincha":
		fallthrough
	case "unicajabanco":
		fallthrough
	case "cajasur":
		fallthrough
	case "kutxabank":
		fallthrough
	case "bankinter":
		fallthrough
	case "renta4":
		fallthrough
	case "BCE":
		fallthrough
	case "laboralkutxa":
		fallthrough
	case "mediolanum":
		fallthrough
	case "openbank":
		fallthrough
	case "ibercaja":
		fallthrough
	case "selfbank":
		fallthrough
	case "inversis":
		fallthrough
	case "andbank":
		fallthrough
	case "wizink":
		*e = PostAutorizacionInicioPagoPathParamAspsp(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostAutorizacionInicioPagoPathParamAspsp: %v", v)
	}
}

type PostAutorizacionInicioPagoPathParamPaymentProduct string

const (
	PostAutorizacionInicioPagoPathParamPaymentProductSepaCreditTransfers             PostAutorizacionInicioPagoPathParamPaymentProduct = "sepa-credit-transfers"
	PostAutorizacionInicioPagoPathParamPaymentProductInstantSepaCreditTransfers      PostAutorizacionInicioPagoPathParamPaymentProduct = "instant-sepa-credit-transfers"
	PostAutorizacionInicioPagoPathParamPaymentProductTarget2Payments                 PostAutorizacionInicioPagoPathParamPaymentProduct = "target-2-payments"
	PostAutorizacionInicioPagoPathParamPaymentProductCrossBorderCreditTransfers      PostAutorizacionInicioPagoPathParamPaymentProduct = "cross-border-credit-transfers"
	PostAutorizacionInicioPagoPathParamPaymentProductDomesticCrossCurrencyPaymentsUk PostAutorizacionInicioPagoPathParamPaymentProduct = "domestic-cross-currency-payments-uk"
	PostAutorizacionInicioPagoPathParamPaymentProductDomesticChapsPaymentsUk         PostAutorizacionInicioPagoPathParamPaymentProduct = "domestic-chaps-payments-uk"
	PostAutorizacionInicioPagoPathParamPaymentProductDomesticFasterPaymentsUk        PostAutorizacionInicioPagoPathParamPaymentProduct = "domestic-faster-payments-uk"
	PostAutorizacionInicioPagoPathParamPaymentProductDomesticBacsPaymentsUk          PostAutorizacionInicioPagoPathParamPaymentProduct = "domestic-bacs-payments-uk"
)

func (e PostAutorizacionInicioPagoPathParamPaymentProduct) ToPointer() *PostAutorizacionInicioPagoPathParamPaymentProduct {
	return &e
}

func (e *PostAutorizacionInicioPagoPathParamPaymentProduct) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "sepa-credit-transfers":
		fallthrough
	case "instant-sepa-credit-transfers":
		fallthrough
	case "target-2-payments":
		fallthrough
	case "cross-border-credit-transfers":
		fallthrough
	case "domestic-cross-currency-payments-uk":
		fallthrough
	case "domestic-chaps-payments-uk":
		fallthrough
	case "domestic-faster-payments-uk":
		fallthrough
	case "domestic-bacs-payments-uk":
		*e = PostAutorizacionInicioPagoPathParamPaymentProduct(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostAutorizacionInicioPagoPathParamPaymentProduct: %v", v)
	}
}

type PostAutorizacionInicioPagoPathParamPaymentService string

const (
	PostAutorizacionInicioPagoPathParamPaymentServicePayments         PostAutorizacionInicioPagoPathParamPaymentService = "payments"
	PostAutorizacionInicioPagoPathParamPaymentServiceBulkPayments     PostAutorizacionInicioPagoPathParamPaymentService = "bulk-payments"
	PostAutorizacionInicioPagoPathParamPaymentServicePeriodicPayments PostAutorizacionInicioPagoPathParamPaymentService = "periodic-payments"
)

func (e PostAutorizacionInicioPagoPathParamPaymentService) ToPointer() *PostAutorizacionInicioPagoPathParamPaymentService {
	return &e
}

func (e *PostAutorizacionInicioPagoPathParamPaymentService) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "payments":
		fallthrough
	case "bulk-payments":
		fallthrough
	case "periodic-payments":
		*e = PostAutorizacionInicioPagoPathParamPaymentService(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostAutorizacionInicioPagoPathParamPaymentService: %v", v)
	}
}

type PostAutorizacionInicioPagoRequest struct {
	// Este dato es contenido si la transacción de inicio de pago forma parte de una sesión (combinación de AIS/PIS). Contendrá el consentId del consentimiento AIS que se realizó previo al inicio de pago. . Ej: Consent-ID: 123-qwer-456
	ConsentID *string `header:"style=simple,explode=false,name=Consent-ID"`
	// Es contenido si viaja el campo Signature. Ej: Digest: SHA-256=NzdmZjA4YjY5M2M2NDYyMmVjOWFmMGNmYTZiNTU3MjVmNDI4NTRlMzJkYzE3ZmNmMDE3ZGFmMjhhNTc5OTU3OQ==
	Digest string `header:"style=simple,explode=false,name=Digest"`
	// Accept header de la petición HTTP entre PSU y el TPP. Ej: PSU-Accept: application/json
	PSUAccept *string `header:"style=simple,explode=false,name=PSU-Accept"`
	// Accept charset header de la petición HTTP entre PSU y el TPP. PSU-Accept-Charset: utf-8
	PSUAcceptCharset *string `header:"style=simple,explode=false,name=PSU-Accept-Charset"`
	// Accept encoding header de la petición HTTP entre PSU y el TPP. PSU-Accept-Language: gzip
	PSUAcceptEncoding *string `header:"style=simple,explode=false,name=PSU-Accept-Encoding"`
	// Accept language header de la petición HTTP entre PSU y el TPP. PSU-Accept-Language: es-ES
	PSUAcceptLanguage *string `header:"style=simple,explode=false,name=PSU-Accept-Language"`
	// UUID (Universally Unique Identifier) para un dispositivo. El UUID identifica al dispositivo o a una instalación de una aplicación en un dispositivo. Este ID no debe ser modificado hasta la desinstalación de la aplicación del dispositivo. Ej: PSU-Device-ID: 5b3ab8e8-0fd5-43d2-946e-d75958b172e7
	PSUDeviceID *string `header:"style=simple,explode=false,name=PSU-Device-ID"`
	// Localización correspondiente a la petición HTTP entre el PSU y el TPP. Ej: PSU-Geo-Location: GEO:90.023856;25.345963
	PSUGeoLocation *string `header:"style=simple,explode=false,name=PSU-Geo-Location"`
	// Método HTTP usado en la interfaz entre PSU y TPP. Valores permitidos: POST. Ej: PSU-Http-Method: POST
	PSUHTTPMethod *string `default:"POST" header:"style=simple,explode=false,name=PSU-Http-Method"`
	// Dirección IP de la petición HTPP entre el PSU y el TPP. Si no está disponible, el TPP debe usar la dirección IP usada por el TPP cuando envía esta petición. Ej: Ej: PSU-IP-Address: 192.168.16.5
	PSUIPAddress string `header:"style=simple,explode=false,name=PSU-IP-Address"`
	// Puerto IP de la petición HTTP entre el PSU y el TPP si está disponible. Ejemplo: PSU-IP-Port: 443
	PSUIPPort *string `header:"style=simple,explode=false,name=PSU-IP-Port"`
	// Navegador o sistema operativo de la petición HTTP entre el PSU y el TPP. Ejemplo: PSU-User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.5) Gecko/20091102 Firefox/3.5.5 (.NET CLR 3.5.30729)
	PSUUserAgent *string `header:"style=simple,explode=false,name=PSU-User-Agent"`
	// Firma de la petición por el TPP.
	Signature string `header:"style=simple,explode=false,name=Signature"`
	// Si esta URI es contenida, el TPP está solicitando redirigir el flujo de la transacción a esta dirección en vez de al TPP-Redirect-URI en caso de un resultado negativo del método de SCA por redirección. "TPP-Nok-Redirect-URI":"https://www.tpp.com/cb/nok"
	TPPNokRedirectURI *string `header:"style=simple,explode=false,name=TPP-Nok-Redirect-URI"`
	// Si es "true", el TPP ha comunicado al HUB que prefiere SCA por redirección. Si es "false", el TPP ha comunicado al HUB que prefiere no ser redireccionado para SCA y el procedimiento será por flujo desacoplado. Si el parámetro no es usado, el ASPSP elegirá el flujo SCA a aplicar dependiendo del método SCA elegido por el TPP/PSU.
	TPPRedirectPreferred *bool `header:"style=simple,explode=false,name=TPP-Redirect-Preferred"`
	// URI del TPP donde el flujo de la transacción debe ser redirigido después de alguna de las fases del SCA. Es recomendado usar siempre este campo de cabecera.En el futuro, este campo podría cambiar a obligatorio. Ej: TPP-Redirect-URI: https://www.tpp.com/cb
	TPPRedirectURI *string `header:"style=simple,explode=false,name=TPP-Redirect-URI"`
	// Certificado del TPP usado para firmar la petición, en base64, sin cabecera, pie ni saltos de linea. Ej: TPP-Signature-Certificate: MIIHgzCCBmugAwIBAgIIZzZvBQlt0UcwDQYJ………….KoZIhvcNAQELBQAwSTELMAkGA1UEBhMCVVMxEzARBgNVBA
	TPPSignatureCertificate string `header:"style=simple,explode=false,name=TPP-Signature-Certificate"`
	// Identificador único de la transacción asignado por el TPP. Ej: X-Request-ID: 1b3ab8e8-0fd5-43d2-946e-d75958b172e7
	XRequestID string `header:"style=simple,explode=false,name=X-Request-ID"`
	// Nombre del ASPSP al que desea realizar la petición.(BBVA, Banco Santander ...)
	Aspsp          PostAutorizacionInicioPagoPathParamAspsp          `pathParam:"style=simple,explode=false,name=aspsp"`
	PaymentID      string                                            `pathParam:"style=simple,explode=false,name=payment-id"`
	PaymentProduct PostAutorizacionInicioPagoPathParamPaymentProduct `pathParam:"style=simple,explode=false,name=payment-product"`
	PaymentService PostAutorizacionInicioPagoPathParamPaymentService `pathParam:"style=simple,explode=false,name=payment-service"`
}

func (p PostAutorizacionInicioPagoRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostAutorizacionInicioPagoRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *PostAutorizacionInicioPagoRequest) GetConsentID() *string {
	if o == nil {
		return nil
	}
	return o.ConsentID
}

func (o *PostAutorizacionInicioPagoRequest) GetDigest() string {
	if o == nil {
		return ""
	}
	return o.Digest
}

func (o *PostAutorizacionInicioPagoRequest) GetPSUAccept() *string {
	if o == nil {
		return nil
	}
	return o.PSUAccept
}

func (o *PostAutorizacionInicioPagoRequest) GetPSUAcceptCharset() *string {
	if o == nil {
		return nil
	}
	return o.PSUAcceptCharset
}

func (o *PostAutorizacionInicioPagoRequest) GetPSUAcceptEncoding() *string {
	if o == nil {
		return nil
	}
	return o.PSUAcceptEncoding
}

func (o *PostAutorizacionInicioPagoRequest) GetPSUAcceptLanguage() *string {
	if o == nil {
		return nil
	}
	return o.PSUAcceptLanguage
}

func (o *PostAutorizacionInicioPagoRequest) GetPSUDeviceID() *string {
	if o == nil {
		return nil
	}
	return o.PSUDeviceID
}

func (o *PostAutorizacionInicioPagoRequest) GetPSUGeoLocation() *string {
	if o == nil {
		return nil
	}
	return o.PSUGeoLocation
}

func (o *PostAutorizacionInicioPagoRequest) GetPSUHTTPMethod() *string {
	if o == nil {
		return nil
	}
	return o.PSUHTTPMethod
}

func (o *PostAutorizacionInicioPagoRequest) GetPSUIPAddress() string {
	if o == nil {
		return ""
	}
	return o.PSUIPAddress
}

func (o *PostAutorizacionInicioPagoRequest) GetPSUIPPort() *string {
	if o == nil {
		return nil
	}
	return o.PSUIPPort
}

func (o *PostAutorizacionInicioPagoRequest) GetPSUUserAgent() *string {
	if o == nil {
		return nil
	}
	return o.PSUUserAgent
}

func (o *PostAutorizacionInicioPagoRequest) GetSignature() string {
	if o == nil {
		return ""
	}
	return o.Signature
}

func (o *PostAutorizacionInicioPagoRequest) GetTPPNokRedirectURI() *string {
	if o == nil {
		return nil
	}
	return o.TPPNokRedirectURI
}

func (o *PostAutorizacionInicioPagoRequest) GetTPPRedirectPreferred() *bool {
	if o == nil {
		return nil
	}
	return o.TPPRedirectPreferred
}

func (o *PostAutorizacionInicioPagoRequest) GetTPPRedirectURI() *string {
	if o == nil {
		return nil
	}
	return o.TPPRedirectURI
}

func (o *PostAutorizacionInicioPagoRequest) GetTPPSignatureCertificate() string {
	if o == nil {
		return ""
	}
	return o.TPPSignatureCertificate
}

func (o *PostAutorizacionInicioPagoRequest) GetXRequestID() string {
	if o == nil {
		return ""
	}
	return o.XRequestID
}

func (o *PostAutorizacionInicioPagoRequest) GetAspsp() PostAutorizacionInicioPagoPathParamAspsp {
	if o == nil {
		return PostAutorizacionInicioPagoPathParamAspsp("")
	}
	return o.Aspsp
}

func (o *PostAutorizacionInicioPagoRequest) GetPaymentID() string {
	if o == nil {
		return ""
	}
	return o.PaymentID
}

func (o *PostAutorizacionInicioPagoRequest) GetPaymentProduct() PostAutorizacionInicioPagoPathParamPaymentProduct {
	if o == nil {
		return PostAutorizacionInicioPagoPathParamPaymentProduct("")
	}
	return o.PaymentProduct
}

func (o *PostAutorizacionInicioPagoRequest) GetPaymentService() PostAutorizacionInicioPagoPathParamPaymentService {
	if o == nil {
		return PostAutorizacionInicioPagoPathParamPaymentService("")
	}
	return o.PaymentService
}

type PostAutorizacionInicioPagoResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP/1.1 201 Created
	ResponseAuthorizationInitiationPayment *shared.ResponseAuthorizationInitiationPayment
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostAutorizacionInicioPagoResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostAutorizacionInicioPagoResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *PostAutorizacionInicioPagoResponse) GetResponseAuthorizationInitiationPayment() *shared.ResponseAuthorizationInitiationPayment {
	if o == nil {
		return nil
	}
	return o.ResponseAuthorizationInitiationPayment
}

func (o *PostAutorizacionInicioPagoResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostAutorizacionInicioPagoResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
