// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DebtorAccount - Cuenta del ordenante
type DebtorAccount struct {
}

// RemunerationAmount - Salario generado en esa unidad de pago
type RemunerationAmount struct {
}

type RequestSocialSecurityWithholding struct {
	// Cuenta del ordenante
	DebtorAccount DebtorAccount `json:"debtorAccount"`
	// Identificador de la empresa empleadora. Solo vendrá relleno opcionalmente cuando paymentNature es 3. Para el resto de casos no existe.
	Niss *int64 `json:"niss,omitempty"`
	// Numero de la seguridad social
	Number int64 `json:"number"`
	// Fecha de realización del pago
	PaymentDate string `json:"paymentDate"`
	// Identifica la categoría profesional a la que pertenece el trabajador
	PaymentNature int64 `json:"paymentNature"`
	// Unidad de pago en función del tipo de remuneración
	PaymentUnit int64 `json:"paymentUnit"`
	// Salario generado en esa unidad de pago
	RemunerationAmount RemunerationAmount `json:"remunerationAmount"`
	// Unidad de pago en función del tipo de remuneración
	RemunerationCode int64 `json:"remunerationCode"`
}

func (o *RequestSocialSecurityWithholding) GetDebtorAccount() DebtorAccount {
	if o == nil {
		return DebtorAccount{}
	}
	return o.DebtorAccount
}

func (o *RequestSocialSecurityWithholding) GetNiss() *int64 {
	if o == nil {
		return nil
	}
	return o.Niss
}

func (o *RequestSocialSecurityWithholding) GetNumber() int64 {
	if o == nil {
		return 0
	}
	return o.Number
}

func (o *RequestSocialSecurityWithholding) GetPaymentDate() string {
	if o == nil {
		return ""
	}
	return o.PaymentDate
}

func (o *RequestSocialSecurityWithholding) GetPaymentNature() int64 {
	if o == nil {
		return 0
	}
	return o.PaymentNature
}

func (o *RequestSocialSecurityWithholding) GetPaymentUnit() int64 {
	if o == nil {
		return 0
	}
	return o.PaymentUnit
}

func (o *RequestSocialSecurityWithholding) GetRemunerationAmount() RemunerationAmount {
	if o == nil {
		return RemunerationAmount{}
	}
	return o.RemunerationAmount
}

func (o *RequestSocialSecurityWithholding) GetRemunerationCode() int64 {
	if o == nil {
		return 0
	}
	return o.RemunerationCode
}
