// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// RequestFundsConfirmationAccount - Número de cuenta del PSU.
type RequestFundsConfirmationAccount struct {
}

// RequestFundsConfirmationInstructedAmount - Contiene la cantidad y moneda a consultar.
type RequestFundsConfirmationInstructedAmount struct {
}

type RequestFundsConfirmation struct {
	// Número de cuenta del PSU.
	Account RequestFundsConfirmationAccount
	// Numeración de la tarjeta emitida por el PIISP. Debe ser enviada si está disponible.
	CardNumber *string
	// Contiene la cantidad y moneda a consultar.
	InstructedAmount RequestFundsConfirmationInstructedAmount
	// Comercio donde la tarjeta es aceptada como información para el PSU.
	Payee *string
}

func (o *RequestFundsConfirmation) GetAccount() RequestFundsConfirmationAccount {
	if o == nil {
		return RequestFundsConfirmationAccount{}
	}
	return o.Account
}

func (o *RequestFundsConfirmation) GetCardNumber() *string {
	if o == nil {
		return nil
	}
	return o.CardNumber
}

func (o *RequestFundsConfirmation) GetInstructedAmount() RequestFundsConfirmationInstructedAmount {
	if o == nil {
		return RequestFundsConfirmationInstructedAmount{}
	}
	return o.InstructedAmount
}

func (o *RequestFundsConfirmation) GetPayee() *string {
	if o == nil {
		return nil
	}
	return o.Payee
}
