// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResponseCancelPaymentInitiationLinks - Lista de hipervínculos para ser reconocidos por el TPP. Dependen de la decisión que tome el ASPSP dinámicamente al evaluar la operación.
type ResponseCancelPaymentInitiationLinks struct {
}

// ResponseCancelPaymentInitiationChoosenScaMethod - NO SOPORTADO EN ESTA VERSIÓN. SOLO EMBEBIDO
type ResponseCancelPaymentInitiationChoosenScaMethod struct {
}

// ResponseCancelPaymentInitiationScaMethods - Este elemento es contenido si SCA es requerido y si el PSU puede elegir entre diferentes métodos de autenticación.
type ResponseCancelPaymentInitiationScaMethods struct {
}

// ResponseCancelPaymentInitiationTppMessages - Mensaje para el TPP enviado a través del HUB.
type ResponseCancelPaymentInitiationTppMessages struct {
}

// ResponseCancelPaymentInitiation - HTTP/1.1 202 Ok
type ResponseCancelPaymentInitiation struct {
	// Lista de hipervínculos para ser reconocidos por el TPP. Dependen de la decisión que tome el ASPSP dinámicamente al evaluar la operación.
	Links *ResponseCancelPaymentInitiationLinks
	// NO SOPORTADO EN ESTA VERSIÓN. SOLO EMBEBIDO
	ChoosenScaMethod *ResponseCancelPaymentInitiationChoosenScaMethod
	// Texto enviado al TPP a través del HUB para ser mostrado al PSU.
	PsuMessage *string
	// Este elemento es contenido si SCA es requerido y si el PSU puede elegir entre diferentes métodos de autenticación.
	ScaMethods *ResponseCancelPaymentInitiationScaMethods
	// Mensaje para el TPP enviado a través del HUB.
	TppMessages *ResponseCancelPaymentInitiationTppMessages
	// Estado de la transacción.
	TransactionStatus string
}

func (o *ResponseCancelPaymentInitiation) GetLinks() *ResponseCancelPaymentInitiationLinks {
	if o == nil {
		return nil
	}
	return o.Links
}

func (o *ResponseCancelPaymentInitiation) GetChoosenScaMethod() *ResponseCancelPaymentInitiationChoosenScaMethod {
	if o == nil {
		return nil
	}
	return o.ChoosenScaMethod
}

func (o *ResponseCancelPaymentInitiation) GetPsuMessage() *string {
	if o == nil {
		return nil
	}
	return o.PsuMessage
}

func (o *ResponseCancelPaymentInitiation) GetScaMethods() *ResponseCancelPaymentInitiationScaMethods {
	if o == nil {
		return nil
	}
	return o.ScaMethods
}

func (o *ResponseCancelPaymentInitiation) GetTppMessages() *ResponseCancelPaymentInitiationTppMessages {
	if o == nil {
		return nil
	}
	return o.TppMessages
}

func (o *ResponseCancelPaymentInitiation) GetTransactionStatus() string {
	if o == nil {
		return ""
	}
	return o.TransactionStatus
}
