// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResponseGetStatusPaymentOwnerNames - Listado de nombres de propietarios de la cuenta.
type ResponseGetStatusPaymentOwnerNames struct {
}

// ResponseGetStatusPaymentTppMessages - Mensaje para el TPP enviado a través del HUB.
type ResponseGetStatusPaymentTppMessages struct {
}

// ResponseGetStatusPayment - HTTP/1.1 200 Ok
type ResponseGetStatusPayment struct {
	// Este dato es contenido si es soportado por el ASPSP, si una confirmación de fondos ha sido realizada y si el “transactionStatus” es ATCT, ACWC, ACCP
	FundsAvailable *bool
	// Listado de nombres de propietarios de la cuenta.
	OwnerNames *ResponseGetStatusPaymentOwnerNames
	// Texto enviado al TPP a través del HUB para ser mostrado al PSU.
	PsuMessage *string
	// Nombre del PSU conectado.En caso de cuentas corporativas, esto podría ser la persona que actúe en nombre de la empresa.
	PsuName *string
	// Mensaje para el TPP enviado a través del HUB.
	TppMessages *ResponseGetStatusPaymentTppMessages
	// Estado de la transacción de pago. Valores definidos en 9.4 Estados de transacción
	TransactionStatus string
}

func (o *ResponseGetStatusPayment) GetFundsAvailable() *bool {
	if o == nil {
		return nil
	}
	return o.FundsAvailable
}

func (o *ResponseGetStatusPayment) GetOwnerNames() *ResponseGetStatusPaymentOwnerNames {
	if o == nil {
		return nil
	}
	return o.OwnerNames
}

func (o *ResponseGetStatusPayment) GetPsuMessage() *string {
	if o == nil {
		return nil
	}
	return o.PsuMessage
}

func (o *ResponseGetStatusPayment) GetPsuName() *string {
	if o == nil {
		return nil
	}
	return o.PsuName
}

func (o *ResponseGetStatusPayment) GetTppMessages() *ResponseGetStatusPaymentTppMessages {
	if o == nil {
		return nil
	}
	return o.TppMessages
}

func (o *ResponseGetStatusPayment) GetTransactionStatus() string {
	if o == nil {
		return ""
	}
	return o.TransactionStatus
}
