// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResponseMultibankSelectSCAMethodLinks - Lista de hipervínculos para ser reconocidos por el TPP
type ResponseMultibankSelectSCAMethodLinks struct {
}

// ResponseMultibankSelectSCAMethodChallengeData - NO SOPORTADO EN ESTA VERSIÓN
type ResponseMultibankSelectSCAMethodChallengeData struct {
}

// ResponseMultibankSelectSCAMethodChosenSCAMethod - NO SOPORTADO EN ESTA VERSIÓN
type ResponseMultibankSelectSCAMethodChosenSCAMethod struct {
}

// ResponseMultibankSelectSCAMethodTppMessages - Mensaje para el TPP enviado a través del HUB.
type ResponseMultibankSelectSCAMethodTppMessages struct {
}

type ResponseMultibankSelectSCAMethod struct {
	// Lista de hipervínculos para ser reconocidos por el TPP
	Links ResponseMultibankSelectSCAMethodLinks `json:"_links"`
	// NO SOPORTADO EN ESTA VERSIÓN
	ChallengeData *ResponseMultibankSelectSCAMethodChallengeData `json:"challengeData,omitempty"`
	// NO SOPORTADO EN ESTA VERSIÓN
	ChosenScaMethod *ResponseMultibankSelectSCAMethodChosenSCAMethod `json:"chosenScaMethod,omitempty"`
	// Texto enviado al TPP a través del HUB para ser mostrado al PSU.
	PsuMessage *string `json:"psuMessage,omitempty"`
	// Estado SCA.
	ScaStatus string `json:"scaStatus"`
	// Mensaje para el TPP enviado a través del HUB.
	TppMessages *ResponseMultibankSelectSCAMethodTppMessages `json:"tppMessages,omitempty"`
}

func (o *ResponseMultibankSelectSCAMethod) GetLinks() ResponseMultibankSelectSCAMethodLinks {
	if o == nil {
		return ResponseMultibankSelectSCAMethodLinks{}
	}
	return o.Links
}

func (o *ResponseMultibankSelectSCAMethod) GetChallengeData() *ResponseMultibankSelectSCAMethodChallengeData {
	if o == nil {
		return nil
	}
	return o.ChallengeData
}

func (o *ResponseMultibankSelectSCAMethod) GetChosenScaMethod() *ResponseMultibankSelectSCAMethodChosenSCAMethod {
	if o == nil {
		return nil
	}
	return o.ChosenScaMethod
}

func (o *ResponseMultibankSelectSCAMethod) GetPsuMessage() *string {
	if o == nil {
		return nil
	}
	return o.PsuMessage
}

func (o *ResponseMultibankSelectSCAMethod) GetScaStatus() string {
	if o == nil {
		return ""
	}
	return o.ScaStatus
}

func (o *ResponseMultibankSelectSCAMethod) GetTppMessages() *ResponseMultibankSelectSCAMethodTppMessages {
	if o == nil {
		return nil
	}
	return o.TppMessages
}
