// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResponseStatusConsentTppMessage - Mensaje para el TPP enviado a través del HUB.
type ResponseStatusConsentTppMessage struct {
}

type ResponseStatusConsent struct {
	// Estado de la transacción (solicitud de consentimiento identificado por consent-id)
	ConsentStatus string
	// Texto enviado al TPP a través del HUB para ser mostrado al PSU.
	PsuMessage *string
	// Mensaje para el TPP enviado a través del HUB.
	TppMessage *ResponseStatusConsentTppMessage
}

func (o *ResponseStatusConsent) GetConsentStatus() string {
	if o == nil {
		return ""
	}
	return o.ConsentStatus
}

func (o *ResponseStatusConsent) GetPsuMessage() *string {
	if o == nil {
		return nil
	}
	return o.PsuMessage
}

func (o *ResponseStatusConsent) GetTppMessage() *ResponseStatusConsentTppMessage {
	if o == nil {
		return nil
	}
	return o.TppMessage
}
