// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResponseAccountBalancesAccount - Identificador de la cuenta que se está consultando.
type ResponseAccountBalancesAccount struct {
}

// Balances de la cuenta
type Balances struct {
}

// TppMessage - Mensaje para el TPP enviado a través del HUB.
type TppMessage struct {
}

type ResponseAccountBalances struct {
	// Identificador de la cuenta que se está consultando.
	Account *ResponseAccountBalancesAccount
	// Balances de la cuenta
	Balances Balances
	// Texto enviado al TPP a través del HUB para ser mostrado al PSU.
	PsuMessage *string
	// Mensaje para el TPP enviado a través del HUB.
	TppMessage *TppMessage
}

func (o *ResponseAccountBalances) GetAccount() *ResponseAccountBalancesAccount {
	if o == nil {
		return nil
	}
	return o.Account
}

func (o *ResponseAccountBalances) GetBalances() Balances {
	if o == nil {
		return Balances{}
	}
	return o.Balances
}

func (o *ResponseAccountBalances) GetPsuMessage() *string {
	if o == nil {
		return nil
	}
	return o.PsuMessage
}

func (o *ResponseAccountBalances) GetTppMessage() *TppMessage {
	if o == nil {
		return nil
	}
	return o.TppMessage
}
