// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResponseGetStatusMultibankPaymentTppMessages - Mensaje para el TPP enviado a través del HUB.
type ResponseGetStatusMultibankPaymentTppMessages struct {
}

type ResponseGetStatusMultibankPayment struct {
	// Este dato es contenido si es soportado por el ASPSP, si una confirmación de fondos ha sido realizada y si el "transactionStatus" es alguno de los siguientes •ACTC•  ACWC•  ACCP
	FundsAvailable *bool `json:"fundsAvailable,omitempty"`
	// Texto enviado al TPP a través del HUB para ser mostrado al PSU.
	PsuMessage *string `json:"psuMessage,omitempty"`
	// Mensaje para el TPP enviado a través del HUB.
	TppMessages *ResponseGetStatusMultibankPaymentTppMessages `json:"tppMessages,omitempty"`
	// Estado de la transacción.
	TransactionStatus string `json:"transactionStatus"`
}

func (o *ResponseGetStatusMultibankPayment) GetFundsAvailable() *bool {
	if o == nil {
		return nil
	}
	return o.FundsAvailable
}

func (o *ResponseGetStatusMultibankPayment) GetPsuMessage() *string {
	if o == nil {
		return nil
	}
	return o.PsuMessage
}

func (o *ResponseGetStatusMultibankPayment) GetTppMessages() *ResponseGetStatusMultibankPaymentTppMessages {
	if o == nil {
		return nil
	}
	return o.TppMessages
}

func (o *ResponseGetStatusMultibankPayment) GetTransactionStatus() string {
	if o == nil {
		return ""
	}
	return o.TransactionStatus
}
